# Docs for the Azure Web Apps Deploy action:
# https://github.com/Azure/webapps-deploy

name: Build and deploy Node.js app to Azure Web App - physioconnect-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "24.x"

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Build app
        working-directory: ./backend
        run: npm run build --if-present

      - name: Run tests
        working-directory: ./backend
        run: npm run test --if-present

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0795ABC0962349FDB29636AC02E2E336 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_72C85F46A26E44C4909280A4EAB97A88 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_25B6666E664E42F198F25702AE501E4C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: physioconnect-api
          slot-name: Production
          package: .
